/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_herodbx_util_GetSocketFd */

#ifndef _Included_org_herodbx_util_GetSocketFd
#define _Included_org_herodbx_util_GetSocketFd
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_herodbx_util_GetSocketFd
 * Method:    getSocketFd
 * Signature: (Ljava/net/Socket;)I
 */
JNIEXPORT jint JNICALL Java_org_herodbx_util_GetSocketFd_getSocketFd
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
